### ISSUE TITLE
Missing e3d_v6_all_metal_hotend.scad and Hexagon-102.scad

### ISSUE THREAD

**Issue by kcleung** [croadfeldt/Roadfeldt_3d_hczf_mount#1]
When I open he_mount_generator.scad, it says complains that e3d_v6_all_metal_hotend.scad and Hexagon-102.scad are missing.  Could you please add them back?

**Comment by TGMods** [comment]
The missing .scad files were never included. You need to download them from the various Thingiverse designs, these designs are referenced in the comments at the start of the he_mount_generator.scad file.
